/*
  silver_census_g01
  Census 2016 G01 (Selected Person Characteristics by Sex) by LGA.
  - lga_code: 'LGA10050' -> 10050 so it joins to the LGA mapping.
  - Every measure column cast from TEXT to integer (generated by looping
    over the source columns, so all 108 measures are typed consistently).
*/
{%- set cols = adapter.get_columns_in_relation(source('bronze', 'raw_census_g01')) -%}

select
    replace(trim(lga_code_2016), 'LGA', '')::int as lga_code
    {%- for col in cols if col.name | lower != 'lga_code_2016' %},
    nullif(trim({{ col.name }}), '')::numeric::int as {{ col.name | lower }}
    {%- endfor %}
from {{ source('bronze', 'raw_census_g01') }}
